### ISSUE TITLE
Calculation speed left to right exagerated

### ISSUE THREAD

**Issue by crobinson42** [gregtinkers/carspeed.py#12]
Any thoughts on why I might have 30-40% inflated speed calculation on vehicles traveling from **left to right** but have a near exact speed calc for vehicles from right to left?

**Comment by gregtinkers** [comment]
The accuracy of right-left vs left-right is very dependent upon the distance from camera to the road. The farther you are away, the less the difference in the distance to the two lanes matters. If you need higher accuracy, modify the program to use a different distance for each direction.

**Comment by crobinson42** [comment]
Thank you, sir. I'll give that shot. Great project btw!
