### ISSUE TITLE
use camera laptop or camera ip 

### ISSUE THREAD

**Issue by ZIKO94ZIKO** [gregtinkers/carspeed.py#15]
HI Sir ,firstly  thank you for sharing your code and make it opensource. Could please explain how can be run the code with camera laptop or using camera ip by RSTP protocol.

**Comment by gregtinkers** [comment]
The program is designed specifically for the Raspberry Pi and its camera. I'd suggest experimenting with  openCV on your laptop and then use CarSpeed as a template for rewriting the code.
