### ISSUE TITLE
findContours line 230 error not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by slowrunner** [gregtinkers/carspeed.py#17]
They changed OpenCV findContours to only return two items now so must change line 230 to:
(cnts, _) = findContours(...

and BTW, if trying this on Buster in Aug 2020, workaround for "undefined symbol: __atomic_fetch_add_8", 
invoke with:
LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1 python3 carspeed.py

**Comment by gregtinkers** [comment]
Yes, the number of parameters appears to have changed in openCV 4.0 from 3 returned items to 2 returned items. I think it changed from 2 to 3 when 3.0 was released. I wish they would make up their minds. 

Thanks for the information on Buster installation.
