### ISSUE TITLE
opencv error: ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by GWAM** [gregtinkers/carspeed.py#18]
Hi Greg, and others!

Unfortunately for me, I am not a developer and don't know how to fix this on my own, I am just dangerous enough to be able to set this up and run it and it has been working great until recently.
It seems that opencv had a few changes to the way the findContours function works and it no longer works with Greg's original code, I get the following error:
```
File "/home/pi/carspeed/carspeed.py", line 228, in <module>
    (_, cnts, _) = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)
```
I tried finding a fix online and folks suggested that this is an opencv version issue, but I really don't know how to fix this, someone suggested:
"...The repository you're addressing is using OpenCV 3.x. However You're using OpenCV 4.x. Output of findContours is changed in OpenCV 4

What variable is missing in OpenCV4?

[As stated in the documentation](https://docs.opencv.org/3.4.17/d3/dc0/group__imgproc__shape.html#gadf1ad6a0b82947fa1fe3c3d497f260e0), OpenCV3's findContours method used to return the source image itself too, which also is unnecessary in your case. If you want to use source image again, you can just create a new variable and call copy = img.copy..."

Would love to see if anyone here can help?
Thanks much!
GWAM

**Comment by gregtinkers** [comment]
I don't have a version running anywhere to test, but try replacing
    (_, cnts, _) = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
with
 cv2.findContours(thresh.copy(), cnts, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

**Comment by GWAM** [comment]
Thanks Greg!! unfortunately, I think the syntax is wrong? with the new line, I get this - 

`NameError: name 'cnts' is not defined`

**Comment by gregtinkers** [comment]
Oops - I think that was the Java syntax. Try this instead.

(cnts, _) = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)

To help you resolve future issues, use this link to the Python OpenCV tutorial:

https://docs.opencv.org/4.x/d6/d00/tutorial_py_root.html

**Comment by GWAM** [comment]
@gregtinkers thank you so much! yes, that worked, I now have the program running again, that's the good news, the bad ones are that post the pandemic and now that schools are back, people yet again speed through our street like maniacs... thanks for the help, I really appreciate it.
M
