### ISSUE TITLE
Similar program

### ISSUE THREAD

**Issue by pageauc** [gregtinkers/carspeed.py#4]
FYI I have a similar python program 
here https://github.com/pageauc/motion-track/tree/master/speed-track-2
This uses multi-processor and has a few more features.  This should run under python3 as well as python2.  See code for details Regards Claude ...

**Comment by gregtinkers** [comment]
@pageauc I'm looking forward to experimenting with your version. I'm guessing that using threading improves the processing speed. I also appreciate the time you have taken to insert comments in your code. Thanks for sharing this.

**Comment by pageauc** [comment]
I just ran it on a RPI3 using the V2 camera.  Speed was pretty amazing.
The RPI I used in the video was a single core that was pretty laggy since I
was not using video stream capture or threading on the original version
speed program. If you run htop you can see the threading working on each
core.  I just posted a speed2.sh script that runs the python script in the
background task to on boot from /etc/rc.local.  The only issue would be
that image files are owned by root when run from rc.local.
Note this runs under python2 but could be easily modified for python3.  I
don't see any speed improvement using python3.

Try using the install.sh script

From ssh session or console terminal perform the following.

    wget
https://raw.github.com/pageauc/motion-track/master/speed-track-2/install.sh
    chmod +x install.sh
    ./install.sh

Any comments would be appreciated
Claude ...

On Fri, Jul 1, 2016 at 10:51 PM, Greg Barbu <notifications@github.com>
wrote:

> @pageauc <https://github.com/pageauc> I'm looking forward to
> experimenting with your version. I'm guessing that using threading improves
> the processing speed. I also appreciate the time you have taken to insert
> comments in your code. Thanks for sharing this.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/gregtinkers/carspeed.py/issues/4#issuecomment-230079907>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFr1ZI5r39lh9qY94QTZaAanBuaheEGDks5qRdJMgaJpZM4JDk41>
> .
>



-- 
See my YouTube Channel at http://www.youtube.com/user/pageaucp

**Comment by RawLiquid** [comment]
I will certainly take a look at this as I've been trying to find the time
to sit down and attempt to make this one multi-threaded. I've just been
busy, thanks for mentioning it

On Friday, July 1, 2016, Claude Pageau <notifications@github.com> wrote:

> FYI I have a similar program here
> https://github.com/pageauc/motion-track/tree/master/speed-track-2
> This uses multi-processor and has a few more features. Regards Claude ...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gregtinkers/carspeed.py/issues/4>, or mute the thread
> <https://github.com/notifications/unsubscribe/AEM5o1g22FzBjigWhu7Obf3aDBgitgZ2ks5qRcJTgaJpZM4JDk41>
> .
>


-- 
I respectfully decline the invitation to join your hallucination.

**Comment by pageauc** [comment]
I have recently updated and improved the install.sh script.  There also was
a bug in the original version.
Delete the original install.sh in /home/pi
rmdir ~/install.sh
cd ~
wget https://raw.github.com/pageauc/motion-track/master/speed-track
-2/install.sh
chmod +x install.sh
./install.sh

See instructions for more detail
Claude ...

On Sun, Jul 3, 2016 at 3:51 AM, RawLiquid <notifications@github.com> wrote:

> I will certainly take a look at this as I've been trying to find the time
> to sit down and attempt to make this one multi-threaded. I've just been
> busy, thanks for mentioning it
>
> On Friday, July 1, 2016, Claude Pageau <notifications@github.com> wrote:
>
> > FYI I have a similar program here
> > https://github.com/pageauc/motion-track/tree/master/speed-track-2
> > This uses multi-processor and has a few more features. Regards Claude ...
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/gregtinkers/carspeed.py/issues/4>, or mute the
> thread
> > <
> https://github.com/notifications/unsubscribe/AEM5o1g22FzBjigWhu7Obf3aDBgitgZ2ks5qRcJTgaJpZM4JDk41
> >
> > .
> >
>
>
> --
> I respectfully decline the invitation to join your hallucination.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/gregtinkers/carspeed.py/issues/4#issuecomment-230140663>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFr1ZIvVaY-ZdTQQz1Z1AnVhDapiE56Rks5qR2oJgaJpZM4JDk41>
> .
>



-- 
See my YouTube Channel at http://www.youtube.com/user/pageaucp

**Comment by pageauc** [comment]
I have recently updated and improved the install.sh script.  There also was
a bug in the original version.
Delete the original install.sh in /home/pi
rm ~/install.sh
cd ~
wget https://raw.github.com/pageauc/motion-track/master/speed-track
-2/install.sh
chmod +x install.sh
./install.sh

See instructions for more detail

On Mon, Jul 4, 2016 at 9:33 AM, Claude Pageau <pageauc@gmail.com> wrote:

> I have recently updated and improved the install.sh script.  There also
> was a bug in the original version.
> Delete the original install.sh in /home/pi
> rmdir ~/install.sh
> cd ~
> wget https://raw.github.com/pageauc/motion-track/master/speed-track
> -2/install.sh
> chmod +x install.sh
> ./install.sh
>
> See instructions for more detail
> Claude ...
>
> On Sun, Jul 3, 2016 at 3:51 AM, RawLiquid <notifications@github.com>
> wrote:
>
>> I will certainly take a look at this as I've been trying to find the time
>> to sit down and attempt to make this one multi-threaded. I've just been
>> busy, thanks for mentioning it
>>
>> On Friday, July 1, 2016, Claude Pageau <notifications@github.com> wrote:
>>
>> > FYI I have a similar program here
>> > https://github.com/pageauc/motion-track/tree/master/speed-track-2
>> > This uses multi-processor and has a few more features. Regards Claude
>> ...
>> >
>> > —
>> > You are receiving this because you are subscribed to this thread.
>> > Reply to this email directly, view it on GitHub
>> > <https://github.com/gregtinkers/carspeed.py/issues/4>, or mute the
>> thread
>> > <
>> https://github.com/notifications/unsubscribe/AEM5o1g22FzBjigWhu7Obf3aDBgitgZ2ks5qRcJTgaJpZM4JDk41
>> >
>> > .
>> >
>>
>>
>> --
>> I respectfully decline the invitation to join your hallucination.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/gregtinkers/carspeed.py/issues/4#issuecomment-230140663>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AFr1ZIvVaY-ZdTQQz1Z1AnVhDapiE56Rks5qR2oJgaJpZM4JDk41>
>> .
>>
>
>
>
> --
> See my YouTube Channel at http://www.youtube.com/user/pageaucp
>



-- 
See my YouTube Channel at http://www.youtube.com/user/pageaucp

**Comment by RawLiquid** [comment]
So in starting with your repo shortly after I commented that I would be trying it out, I initially had a number of difficulties, I'm not sure why but a couple of function calls were not working properly, I think one was missing a parameter, I had tried first with python3, then after fixing a few issues I ran into one that wasn't clear exactly how to resolve, so I tried it in python2 and ended up having to change a couple other items to get it to run.
I will have to check the source now,  but for all I know it's entirely possible that one of the big bugs I fixed was my own creation.
I currently have  fairly reliable vehicle detection, it's still pretty dim out due to overcast, but when a vehicle is detected, it seems to be pretty solid, or it simply isn't detected at all.
one thing that is making me raise an eyebrow is the numbers I'm suddenly seeing. What kind of FPS are you guys getting using Claude's script?
I want to say initially I was showing somewhere in the 20-25 range, but detection was NOT working at all, due to the previously mentioned bug, and substantial wind...
My next modification right now will be to only run detection on the full frame when the option to show out of range is enabled, and crop the frame when it is not. that should boost the framerate when the wind is blowing and thus causing hits all over the frame.

**Comment by pageauc** [comment]
If you are running my script speed2.py I have not tested it for python3 but
did build some code in for detecting if it was running under python 3.  I
have only run under python2 due to having to compile python3 from source
which I have done in the past but do not have subsequently reused that sd
card.

I would recommend you just run the install.sh script again per instructions
on my github repo.  This will upgrade the existing files with my github
repo per instructions..

https://github.com/pageauc/motion-track/tree/master/speed-track-2

If you can test python 3 in another folder then let me know if it has
problems which it sounds like it does.  There are differences between
opencv ver 3 syntactially and I have done some previous testing but did not
find Any performance improvement using with python3 over python2

Thanks Claude ..

On Wed, Jul 6, 2016 at 11:48 AM, RawLiquid <notifications@github.com> wrote:

> So in starting with your repo shortly after I commented that I would be
> trying it out, I initially had a number of difficulties, I'm not sure why
> but a couple of function calls were not working properly, I think one was
> missing a parameter, I had tried first with python3, then after fixing a
> few issues I ran into one that wasn't clear exactly how to resolve, so I
> tried it in python2 and ended up having to change a couple other items to
> get it to run.
> I will have to check the source now, but for all I know it's entirely
> possible that one of the big bugs I fixed was my own creation.
> I currently have fairly reliable vehicle detection, it's still pretty dim
> out due to overcast, but when a vehicle is detected, it seems to be pretty
> solid, or it simply isn't detected at all.
> one thing that is making me raise an eyebrow is the numbers I'm suddenly
> seeing. What kind of FPS are you guys getting using Claude's script?
> I want to say initially I was showing somewhere in the 20-25 range, but
> detection was NOT working at all, due to the previously mentioned bug, and
> substantial wind...
> My next modification right now will be to only run detection on the full
> frame when the option to show out of range is enabled, and crop the frame
> when it is not. that should boost the framerate when the wind is blowing
> and thus causing hits all over the frame.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/gregtinkers/carspeed.py/issues/4#issuecomment-230814446>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFr1ZDnpUmszKlUApAwG_Gho9yaa7fwjks5qS85GgaJpZM4JDk41>
> .
>



-- 
See my YouTube Channel at http://www.youtube.com/user/pageaucp

**Comment by RawLiquid** [comment]
btw, the main bug I found and fixed was my mistake, the error I was getting had to do with the syntax for the threshold bits, and I had changed the image it was using while trying to figure out what the issue was, and forgot to change it back...

I've definately had much better results by blurring the gray images before the comparison rather than blurring the absolute difference. Blurring after results in many more contours located vs the average of 4-8 contours by blurring before. Let me fork it so I can do a direct comparison and possibly merge in some of the changes I made, among those, I like being able to show a detection flow so I can see what  exactly is being seen by each step of the program, it helps alot being able to see that as it's happening so you can pick out what might be removing a positive from showing up, another change I made is if the gui windows are being shown, I put the last vehicle image into its own window, which also makes it easy to tell if a vehicle I just heard or saw go by was captured or not.

Currently, the one I'm running is reporting an average of 80 fps, that is without the windows showing, but wow...what a difference from struggling to get 15fps out of it...

**Comment by pageauc** [comment]
RawLiquid

I am assuming you are running my version called speed2.py rather than the gregtinkers/carspeed.py?
If so I am curious if were you able to run it OK under python3..  Let me know. 

Also
I was thinking of trying to add an optional feature to saving all completed track x,y coordinates to a file.  That way it could be used to track flying birds or other objects. cars normally move in a straight line.  I would have to add max area as well as the minimum area.  That way you could restrict tracking to very small moving contours if desired.  not just eg trees, plants Etc moving that might generate a contour but not a track.

**Comment by RawLiquid** [comment]
Sorry I sorta fell off the wagon here for a bit, Had a number of things going on but I should be getting back to helping with this soon, though my first task will be to figure out a stationary place I can place the thing where it can't be stepped on...

I'm definatly still stuck with the feeling that the camera could be doing alot of this work, do a better job of it, and free up the pi to simply filter the data and pick a frame that has the vehicle in it...Then there would be all kinds of processor time available for things like logging the data to a database, or serving up a basic apache server so the community can see the worst offending vehicles...who knows what else...

Greg, I don't suppose you know anything about accessing the motion estimation data the camera can send?

**Comment by gregtinkers** [comment]
@RawLiquid Sorry, I know the camera can capture motion vectors and it theoretically could duplicate what carspeed is doing. I just have no idea how to make use of them and I'm already off working on another project. I'd say a Google search for "picamera motion vectors" is in order.

**Comment by RawLiquid** [comment]
Yah, I did find a program that works quite well for detecting motion using the vector data, and one of the things it will do is show the resulting info on the preview, in the form of a line extending from the object in the direction of travel, based on the speed of the movement...I started looking at the code behind it but some other responsibilities got in the way and I haven't gotten back to it yet. the app I found lets you set up as many detection zones as you want, with the video running at a high resolution, I wanna say 720p from memory but really its slipped my mind, I know you can change it to whatever you want. but it will then record clips of motion, or take pics, and it does all of this via an embedded web server over the network....
