### ISSUE TITLE
carspeed.py will not launch + new to python. 

### ISSUE THREAD

**Issue by dirtybeagles** [gregtinkers/carspeed.py#6]
First, I am brand new into the python scene but the tutorials to get opencv install and all the dependencies were pretty simple(from: http://www.pyimagesearch.com/2015/10/26/how-to-install-opencv-3-on-raspbian-jessie/). I compiled my image (named picamera) with Python3 and I did not receive any errors. I complete the install fine from what I can tell. My issue is when I am 
`workon picamera` and try to start python `carspeed.py` I keep getting this error:

`(picamera) pi@raspberrypi:~ $ python carspeed.py`
  `File "carspeed.py", line 5`
    `<!DOCTYPE html>`
    `^`
`SyntaxError: invalid syntax`

I am assuming it is a simple fix because I feel I am missing something but I have gone through the guide a few times and still end up with this same error. Also, if I try to launch through raspbian OS through, I receive the same error. Thanks for the help.  

picture attached: 
![pic1](https://cloud.githubusercontent.com/assets/9894207/18694940/3ba81cc6-7f7c-11e6-8342-8a6afee4685e.png)

**Comment by gregtinkers** [comment]
It looks like you have copied some of HTML code into your carspeed.py file. You may wish to use the green 'Clone or download' button on the carspeed page to download a zip file of the program. That will get you a copy without any HTML in it.

**Comment by dirtybeagles** [comment]
Wow that was easy. I just downloaded it to my pc and WINSCP it over and it started just fine.

Should I open a new topic if I want to know how I could change the snap shot directory to an SMB share? 
Also, is there a live stream function to access remotely?

**Comment by gregtinkers** [comment]
When I started this project I wasn't experienced with python either, but I researched on-line and figured out how to put the pieces together to make it work. Line 268 writes the image. I'm sure you can find resources on-line to explain how to write to an SMB share. I don't line stream the video, but I do access the Pi with VNC to monitor it while it is running.
