### ISSUE TITLE
X location will be incorrect

### ISSUE THREAD

**Issue by kubilus1** [gregtinkers/carspeed.py#7]
>     # examine the contours, looking for the largest one
    for c in cnts:
        (x, y, w, h) = cv2.boundingRect(c)
        # get an approximate area of the contour
        found_area = w*h 
        # find the largest bounding rectangle
        if (found_area > MIN_AREA) and (found_area > biggest_area):  
            biggest_area = found_area
            motion_found = True

    if motion_found:
        if state == WAITING:
            # intialize tracking
            state = TRACKING
            initial_x = x
            last_x = x

There is a bug in the above code.  x will not be from the largest contour, but from the *last* contour  found.  This can lead to erroneous results.

**Comment by gregtinkers** [comment]
@kubilus1 You are correct. That bug was discovered a couple weeks ago - the corrected code is in the comments on the [gregtinkers site](https://gregtinkers.wordpress.com/2016/03/25/car-speed-detector/) I'm working on version 2 and should have it posted in a day or so.
