### ISSUE TITLE
Does FOV change based upon 1080p vs 720p....

### ISSUE THREAD

**Issue by picameratk** [gregtinkers/carspeed.py#9]
When I put in a distance from my camera to the street carspeed.py calculates the length according to trig.  However when I measure the distance of my field of view (FOV) I come up with a shorter length.

My process. 
1. Use laser measuring device to measure to center of street and get 91 ft.   carspeed.py calculates 109 feet for the length.
2. Used a laser pointer to measure the length and I get around 96 1/2 ft which is vastly shorter than calculated.  Note that I stand out front while another person watches the carspeed video session to direct me to the edges of the screen.
3. Since I believe the trig calc therefore I believe carspeed.py is calculating the length correctly IF I provided the proper FOV.  According to the documentation I have found, https://www.raspberrypi.org/documentation/hardware/camera/  for camera module 2 the FOV is 62.2.  I am running the camera in 1280x720 mode.

All I can think is that somehow the FOV is wrong or my methodology for measure the distance is wrong.

So, does FOV change if the dimensions of the camera are input as 1920x1280 vs 1280x720?

Environment:
1. Raspberry Pi 3
2. Raspian Jessie
3. OpenCV 3.2
4. Python 2.7.9
5. Raspberry Pi Camera Module V2

P.S. I did    pip install "picamera[array]" .  Does this work for Camera Module V2?

**Comment by gregtinkers** [comment]
Yes, it looks like the FOV does change, and the change is different for V2. See http://picamera.readthedocs.io/en/release-1.12/fov.html for more information. If you know the exact distance from the sides of the frame at 91 ft, plug it into **frame_width_ft** to get accurate results. I believe picamerea[array] does work with V2, but I have not tested it myself.

**Comment by picameratk** [comment]
Thank you gregtinkers;  you found the documentation that has thus far eluded me.  I think I will actually change the resolution to 1640x922 to get full FOV as per the documentation. 

Thanks again.
